#!/bin/bash
set -eu
if [[ $$ != 1 ]]; then
  echo 'This wrapper must run as PID 1.' >&2
  exit 1
fi
mkdir -p /run/systemd
if [[ ! -f /sys/fs/cgroup/cgroup.controllers ]]; then
  mount -t cgroup2 none /sys/fs/cgroup
fi
exec /sbin/init --show-status=true
